# demo-nodeaffinity-required.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nodeaffinity-required
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "disk"
                operator: In
                values:
                  - ssd
  template:
    spec:
      metadata:
        labels:
          app: nginx
      containers:
        - name: nginx
          image: nginx