# demo-rs-existing.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-rs-existing
spec:
  replicas: 2 # only 2, less than existing pod
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: demo-rs
      labels:
        app: nginx
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: nginx